### ISSUE TITLE
Can this library add a thumb instead of percentage text? 

### ISSUE THREAD

**Issue by ghost** [DevLight-Mobile-Agency/ArcProgressStackView#3]
For a reason, I want to use it for a clock picker, start o'clock and end o'clock. There is not a thumb especially when the angle is 0.

**Comment by GIGAMOLE** [comment]
Hello. Unforrtunetly, no. But you can set transparent titles color to apsv and add textviews over apsv dirrectly near your start and end angle. Thanks.
