### ISSUE TITLE
A little bug when using in floatwindow

### ISSUE THREAD

**Issue by luzhzhsoft** [DevLight-Mobile-Agency/ArcProgressStackView#4]
Hello ,i am form china .you project is very good .But i find a little bug in your project .When I use your lib in floatwindow ,it draw twice.I think it may because you use shadow layer,but i do not konw why.
please see the image.

[https://github.com/luzhzhsoft/MonkeyApplication/blob/master/app/src/main/res/drawable/Screenshot_2016-05-11-11-11-44.png](url)

**Comment by luzhzhsoft** [comment]
[https://github.com/luzhzhsoft/MonkeyApplication/blob/master/app/src/main/res/drawable/Screenshot_2016-05-11-11-11-44.png?raw=true](url)

**Comment by GIGAMOLE** [comment]
Hello. Thanks for feedback. What is float window? And can you provida avilable link.
