### ISSUE TITLE
ArcProgressStackView is being redrawn constantly

### ISSUE THREAD

**Issue by qwertyfinger** [DevLight-Mobile-Agency/ArcProgressStackView#6]
Whenever there is ArcProgressStackView with Model attached to it, it's being constantly redrawn. And one of my devices' log is flooded with messages like this:

> D/Surface: Surface::setBuffersDimensions(this=0x7faee0d400,w=1080,h=1920)

This can be seen even in example app.
However, on other devices there's no such messages but if you enable 'hardware layers updates' or 'gpu view updates' in developer options, you'll see exactly the same thing - ArcProgressStackView is flashed all the time.

**Comment by GIGAMOLE** [comment]
Hello. Interesting. Ill try to find what the problem. If you can also. Come up with some request.

**Comment by GIGAMOLE** [comment]
Hello. Update 1.0.3 is on the rails. I have been fix this bug. Thanks.

**Comment by qwertyfinger** [comment]
Glad to hear it.
Keep up the good work, fellow Ukrainians.
