### ISSUE TITLE
help..

### ISSUE THREAD

**Issue by divya2392** [DevLight-Mobile-Agency/ArcProgressStackView#8]
I want to add this library in my project but when i added dependency it give me error so please can u tell me where i have to write this i think i am adding in a wrong way.. reply as soon as possible

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue. Have you ever compile my lib. If yes, try to clean .gradle folder.

**Comment by divya2392** [comment]
Hi , Thank u for reply i solved it :) :)
