### ISSUE TITLE
ArcProgressStackView.animateProgress() to animate only a specific model

### ISSUE THREAD

**Issue by vysakhvasanth** [DevLight-Mobile-Agency/ArcProgressStackView#9]
Hi,
I am currently using 2 models and tracking two different values. I noticed that once I change the value on one of the model and call animateProgress(), both of them animate. I had a look at the demo app for some guidance, but couldn't find anything relevant. Is it possible to have a model.animateProgress() or animateProgress(model)?  

_Note: If I don't call the animateProgress, they work fine and each updates independently._

Also this is an awesome library :+1: 
Thanks

**Comment by GIGAMOLE** [comment]
Hello.
Thanks for question.

As you can see, we animate all APSV where it loop trough models and animate progress from last to new. So, if you want to animate only one progress, you must to change one model progress and call animateProgress(). So it will animate and second progress will not change.

**Comment by vysakhvasanth** [comment]
I am updating them separately and calling the animateProgress. The behavior I get is that _all models_ get redrawn (to the current progress) when the animateProgress is called.

**Comment by GIGAMOLE** [comment]
As a problem you have, you need to animate only one progress? AnimateProgress() method works using AnimatorUpdateListener which trigger on each frame postInvalidate() which redraw all view and all models progresses. So you need to change only one model progress and call animateProgress().

**Comment by vysakhvasanth** [comment]
Ahh okay. I had two models updating periodically (one every second and another on a callback). So I called animateProgress() when each progress was updated. Thanks for the help.
